### ISSUE TITLE
Duplicate external links on docs/xcm/index.md

### ISSUE THREAD

**Issue by chrisli30** [AstarNetwork/astar-docs#193]
A nit-pick, I found that link of two items on [this XCM page](https://github.com/AstarNetwork/astar-docs/blob/main/docs/xcm/index.md) are the same, as shown below.

- [Sub0 - Getting Started with XCM](https://www.youtube.com/watch?v=5cgq5jOZx9g)
- [How to make a cross-chain transfer](https://www.youtube.com/watch?v=5cgq5jOZx9g)

**Comment by meganskye** [comment]
we've restructured the docs recently so this no longer applies, thank you for the report.
