### ISSUE TITLE
Astar.js cookbook on 2 places

### ISSUE THREAD

**Issue by Maar-io** [AstarNetwork/astar-docs#275]
There is PR to introduce Astar.js for Wasm and there is this document under XWM/WASM
https://docs.astar.network/docs/build/builder-guides/xvm_wasm/interact_with_wasm_contract

Make it unified and relevant

**Comment by niklabh** [comment]
Can i move this to docs/build/wasm/interact/astarjs.md

**Comment by niklabh** [comment]
Unified https://github.com/AstarNetwork/astar-docs/pull/270/files
