### ISSUE TITLE
Need Links to API Documentation

### ISSUE THREAD

**Issue by Luzzotica** [AstarNetwork/astar-docs#298]
Lots of references to thing like the `pallet-contracts` API, but no link to them.

See [here](https://docs.astar.network/docs/build/wasm/smart-contract-wasm).

I still haven't found a link to those API docs, or I would start editing each page and adding it myself as a PR.

**Comment by midegdugarova** [comment]
https://github.com/AstarNetwork/astar-docs/commit/adf6a1144268bf52d1c3df4d0324606ae7c1a765 
links added
