### ISSUE TITLE
Create a Glossary

### ISSUE THREAD

**Issue by Luzzotica** [AstarNetwork/astar-docs#299]
The first step to understanding any new system is to first know the vocabulary.

Right now, the documentation has a simple vocab list in the `Ecosystem` area, but it is by no means comprehensive, nor does it dive into the deeper tools and resources I would need to understand each piece of Astar and work with it.

Some examples of questions I would really like the answer to:
what is Shiden? How is it related to Astar?
You have a definition of substrate, and I'm assuming that Astar has used it to build their blockchain, but is that it? Does it do anything else for Astar? How has it influenced Astar?
What is Ink! and eDSL? I don't know rust yet, so these questions may be stupid. 

For each layer deeper, I would recommend creating a glossary for the information you will need to understand the guides/tutorials/content that is written at that layer, and provide links to outside resources in the glossary. Ink! is an example of where this would be helpful.

**Comment by midegdugarova** [comment]
https://docs.astar.network/docs/about/glossary
