### ISSUE TITLE
Problems Astar Solves is Unhelpful

### ISSUE THREAD

**Issue by Luzzotica** [AstarNetwork/astar-docs#300]
[This](https://docs.astar.network/docs/about/astar) page is unhelpful.

Everyone says their blockchain does this.

I would recommend fleshing it out a bit more and perhaps linking your whitepaper so people can understand **how** you're tackling those problems and **why** your solution will actually work.

**Comment by midegdugarova** [comment]
thank you @Luzzotica for your comments, we will address them ASAP!

**Comment by meganskye** [comment]
we've restructured the docs recently and addressed the issue. thank you for the report.
