### ISSUE TITLE
Missing guide on how to interact with Shibuya <> Shinjuku environment

### ISSUE THREAD

**Issue by andabak** [AstarNetwork/astar-docs#304]
There is a diagram which indicates a "Token Parachain Testnet" which is in fact Shinjuku but there is no more detail on how would a person interact with it and in which situations.
https://docs.astar.network/docs/build/Introduction/astar_family

Shinjuku <> Shibuya testnet environment is important as a place to test XCM interactions and smart contract interactions in future (when XCM Chain Extension becomes available)

**Comment by meganskye** [comment]
hi Ivan i have added this to the current astar docs task queue to be addressed in priority sequence. if there is any new information applicable to this ticket (ie: about the XCM chain extension), please add it somewhere for visibility, thank you.
