### ISSUE TITLE
Missing images in chapter building-with-xcm

### ISSUE THREAD

**Issue by Maar-io** [AstarNetwork/astar-docs#323]
https://docs.astar.network/docs/xcm/building-with-xcm/native-transactions#initial-state

**Comment by meganskye** [comment]
a new copy of the document is at https://docs.astar.network/docs/learn/xcm/building-with-xcm/native-transactions#initial-state 

is this issue resolved now Maar-io?

**Comment by meganskye** [comment]
it appears this issue has been resolved. if not, please open another trouble ticket, thank you.
