### ISSUE TITLE
Repeated sentence in Ecosystem-> Polkadot section

### ISSUE THREAD

**Issue by josip-simunovic88** [AstarNetwork/astar-docs#341]
https://docs.astar.network/docs/ecosystem/polkadot

The sentence "Astar Network is built on Parity Substrate making it one of the first SCALABLE smart contract Polkadot Parachains."  is written twice in a sequence.

**Comment by meganskye** [comment]
ooooh~ nice find, thank you. this has been addressed now in the meganFixLinks branch.
