### ISSUE TITLE
link in the tutorial using openbrush doesn't work 

### ISSUE THREAD

**Issue by mshankarrao** [AstarNetwork/astar-docs#400]
I was trying the tutorial for the psp22 and psp34 as a part of Astar university but the project generated by the openbrush has issues and doesn't compile
https://docs.astar.network/docs/build/wasm/from-zero-to-ink-hero/nft/Wizard/#use-the-wizard-to-generate-generic-psp34-code

**Comment by meganskye** [comment]
this issue appears to have been resolved. thank you for the submission.
