### ISSUE TITLE
Need to update the astar-collator options

### ISSUE THREAD

**Issue by tksarah** [AstarNetwork/astar-docs#401]
According to astar-collator latest version, 
I found that some command options are replaced.

https://github.com/paritytech/substrate/pull/13384

we should update below the document for RasPi.

https://docs.astar.network/docs/nodes/rpi-cheat-sheet/

for example, "--ws-external" can not use with v5.15.

@meganskye

**Comment by bLd75** [comment]
https://github.com/AstarNetwork/astar-docs/pull/402
