### ISSUE TITLE
Some problems on "Integrations > Indexers > The Graph" page

### ISSUE THREAD

**Issue by koutakou** [AstarNetwork/astar-docs#41]
Hi !!
I found some small problems on "The Graph" page (https://docs.astar.network/docs/integrations/indexers/thegraph)

- The script in "One-line startup script" that no longer exists (https://raw.githubusercontent.com/AstarNetwork/Astar/rpc-script/scripts/graph.sh) 
![image](https://user-images.githubusercontent.com/2778130/182035960-e65866c1-248a-4b27-8224-e06d0a679762.png)

- Typo problems in the "Running Graph node" in the github link to clone the repo --> `git clone <https://github.com/graphprotocol/graph-node/>` instead of  `git clone https://github.com/graphprotocol/graph-node/` 
![image](https://user-images.githubusercontent.com/2778130/182036015-977ea858-6997-4b32-8386-ed837d157730.png)

- I suggest to use https in the complete example of the docker-compose.yml for the consistency (I was tricked into copying and pasting ahah)
![image](https://user-images.githubusercontent.com/2778130/182036100-d0d75155-639c-450f-8241-77c5429d26dd.png)

I hope this issue is relevant ;)

**Comment by andabakus** [comment]
Thanks for opening the issue! We will put this into our pipeline and update the docs.

**Comment by andabakus** [comment]
https://github.com/AstarNetwork/astar-docs/pull/55 solved this issue. Closing issue.
