### ISSUE TITLE
Broken Subquery link for zKatana

### ISSUE THREAD

**Issue by Maar-io** [AstarNetwork/astar-docs#480]
<img width="759" alt="Screenshot 2023-10-20 at 14 48 42" src="https://github.com/AstarNetwork/astar-docs/assets/34627453/e1784e80-027f-4bc9-9cac-3d80e3771167">

Please visit the quickstart guide [here](https://academy.subquery.network/quickstart/quickstart_chains/astar-zkatana.html) 
@meganskye

**Comment by meganskye** [comment]
according to SubQuery team this link will go live next monday.

**Comment by meganskye** [comment]
this issue has been resolved now. thank you for the submission
